site_name: Bootstrap.jl

site_description: Bootstrapping statistic framework for the Julia programming language

theme: readthedocs

repo_url: https://github.com/julian-gehring/Bootstrap.jl

pages:
- Introduction: 'index.md'
- Notebooks: 'notebooks.md'
- API: 'api.md'
- References: 'references.md'
- About:
  - 'License': 'LICENSE.md'

docs_dir: doc

site_favicon: null

markdown_extensions: [codehilite, def_list]
